apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ball
    version: v2
  name: ball-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ball
      version: v2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: true
        prometheus.io/port: 9090
      labels:
        app: ball
        version: v2
    spec:
      containers:
      - image: jotak/demo-mesh-arena-ball:latest
        imagePullPolicy: IfNotPresent
        name: ball
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: localhost
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadium
        - name: IMAGE
          value: "ballv2"
        securityContext:
          privileged: false
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
