# Scenario 3: 50-50
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ball-vs
spec:
  hosts:
  - ball
  http:
  - route:
    - destination:
        host: ball
        subset: ball-v1
      weight: 50
    - destination:
        host: ball
        subset: ball-v2
      weight: 50
