---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ball-vs
spec:
  hosts:
  - ball
  http:
  - route:
    - destination:
        host: ball
        subset: ball-v1
      weight: 25
    - destination:
        host: ball
        subset: ball-v2
      weight: 75

#---
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: ball-vs
#spec:
#  hosts:
#  - ball
#  http:
#  - match:
#    # doesn't work... because of this? https://github.com/istio/istio/issues/7787
#    - sourceLabels:
#        version: goat
#    route:
#    - destination:
#        host: ball
#        subset: ball-v1
#  - route:
#    - destination:
#        host: ball
#        subset: ball-v2
