apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  labels:
    app: kiali
    # version: ${VERSION_LABEL}
data:
  config.yaml: |
    server:
      port: 20001
      web_root: /
    api:
      namespaces:
        exclude:
          - istio-operator
          - kube.*
    # external_services:
    #   jaeger:
    #     url: ${JAEGER_URL}
    #   grafana:
    #     url: ${GRAFANA_URL}
