apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: stadium
    version: small
  name: stadium-small
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stadium
      version: small
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/port: "9090"
        kiali.io/dashboards: vertx
      labels:
        app: stadium
        version: small
    spec:
      containers:
      - image: jotak/demo-mesh-arena-stadium:1.1
        imagePullPolicy: IfNotPresent
        name: stadium
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: METRICS_ENABLED
          value: "0"
        - name: AB_OFF
          value: "1"
        - name: JAVA_OPTIONS
          value: "-Dvertx.disableDnsResolver=true"
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: ball
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: STADIUM_LOCALS
          value: Locals
        - name: STADIUM_VISITORS
          value: Visitors
        - name: STADIUM_NAME
          value: Commanderie
        - name: STADIUM_TOP
          value: "50"
        - name: STADIUM_LEFT
          value: "20"
        - name: STADIUM_SCALE
          value: "1.0"
        - name: STADIUM_MATCH_TIME
          value: "120"
        securityContext:
          privileged: false
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
