apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: stadium
    version: big
  name: stadium-big
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stadium
      version: big
  template:
    metadata:
      annotations:
        prometheus.io/scrape: true
        prometheus.io/port: 9090
      labels:
        app: stadium
        version: big
    spec:
      containers:
      - image: jotak/demo-mesh-arena-stadium:latest
        imagePullPolicy: IfNotPresent
        name: stadium
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: ball
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: localhost
        - name: STADIUM_LOCALS
          value: Locals
        - name: STADIUM_VISITORS
          value: Visitors
        - name: STADIUM_NAME
          value: Vélodrome
        - name: STADIUM_TOP
          value: "500"
        - name: STADIUM_LEFT
          value: "20"
        - name: STADIUM_SCALE
          value: "1.4"
        - name: STADIUM_MATCH_TIME
          value: "300"
        securityContext:
          privileged: false
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
