apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ai-visitors
    version: basic
  name: ai-visitors-basic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-visitors
      version: basic
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        kiali.io/dashboards: vertx
      labels:
        app: ai-visitors
        version: basic
    spec:
      containers:
      - image: jotak/demo-mesh-arena-ai:1.1
        imagePullPolicy: IfNotPresent
        name: ai-visitors
        env:
        - name: METRICS_ENABLED
          value: "1"
        - name: AB_OFF
          value: "1"
        - name: JAVA_OPTIONS
          value: "-Dvertx.disableDnsResolver=true"
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: ball
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadium
        - name: PLAYER_TEAM
          value: visitors
        - name: PLAYER_COLOR
          value: yellow
        - name: PLAYER_NAME
          value: une chèvre jaune
        securityContext:
          privileged: false
