apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ai-locals
    version: mbappe
  name: ai-locals-mbappe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-locals
      version: mbappe
  template:
    metadata:
      annotations:
        prometheus.io/scrape: true
        prometheus.io/port: 9090
      labels:
        app: ai-locals
        version: mbappe
    spec:
      containers:
      - image: jotak/demo-mesh-arena-ai:latest
        imagePullPolicy: IfNotPresent
        name: ai-locals
        env:
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: ball
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadium
        - name: PLAYER_TEAM
          value: locals
        - name: PLAYER_NAME
          value: "Mbappé"
        - name: PLAYER_SPEED
          value: 95
        - name: PLAYER_ACCURACY
          value: 0.89
        - name: PLAYER_SKILL
          value: 11
        - name: PLAYER_SHOOT
          value: 300
        - name: PLAYER_ATTACKING
          value: 90
        - name: PLAYER_ATT_SHOOT_FAST
          value: 20
        - name: PLAYER_DEF_SHOOT_FAST
          value: 40
        - name: PLAYER_COLOR
          value: cyan
        securityContext:
          privileged: false
