apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ai-locals
    version: basic
  name: ai-locals-basic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-locals
      version: basic
  template:
    metadata:
      annotations:
        prometheus.io/scrape: true
        prometheus.io/port: 9090
        kiali.io/runtime: vertx
      labels:
        app: ai-locals
        version: basic
    spec:
      containers:
      - image: jotak/demo-mesh-arena-ai:1.0-metrics
        imagePullPolicy: IfNotPresent
        name: ai-locals
        env:
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: ball
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadium
        - name: PLAYER_TEAM
          value: locals
        - name: PLAYER_COLOR
          value: blue
        - name: PLAYER_NAME
          value: une chèvre bleue
        securityContext:
          privileged: false
