apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ai-visitors
    version: PSG
  name: ai-visitors-psg
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ai-visitors
      version: PSG
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/port: "9090"
        kiali.io/runtimes: vertx-client,vertx-pool
      labels:
        app: ai-visitors
        version: PSG
    spec:
      containers:
      - image: jotak/demo-mesh-arena-ai:1.1.1
        imagePullPolicy: IfNotPresent
        name: ai-locals
        env:
        - name: METRICS_ENABLED
          value: "0"
        - name: AB_OFF
          value: "1"
        - name: JAVA_OPTIONS
          value: "-Dvertx.disableDnsResolver=true"
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: ball
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadium
        - name: PLAYER_TEAM
          value: visitors
        - name: PLAYER_NAME
          value: "joueur du PSG"
        - name: PLAYER_SPEED
          value: 75
        - name: PLAYER_ACCURACY
          value: 0.85
        - name: PLAYER_SKILL
          value: 8
        - name: PLAYER_SHOOT
          value: 280
        - name: PLAYER_ATTACKING
          value: 80
        - name: PLAYER_ATT_SHOOT_FAST
          value: 20
        - name: PLAYER_DEF_SHOOT_FAST
          value: 40
        - name: PLAYER_COLOR
          value: purple
        securityContext:
          privileged: false
