apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ai-visitors
    version: basic
  name: ai-visitors-basic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-visitors
      version: basic
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/port: "9090"
        kiali.io/runtimes: vertx-client,vertx-pool
      labels:
        app: ai-visitors
        version: basic
    spec:
      containers:
      - image: jotak/demo-mesh-arena-ai:1.1.1
        imagePullPolicy: IfNotPresent
        name: ai-visitors
        env:
        - name: METRICS_ENABLED
          value: "0"
        - name: AB_OFF
          value: "1"
        - name: JAVA_OPTIONS
          value: "-Dvertx.disableDnsResolver=true"
        - name: MESHARENA_UI_PORT
          value: "8080"
        - name: MESHARENA_UI_HOST
          value: ui
        - name: MESHARENA_BALL_PORT
          value: "8080"
        - name: MESHARENA_BALL_HOST
          value: ball
        - name: MESHARENA_STADIUM_PORT
          value: "8080"
        - name: MESHARENA_STADIUM_HOST
          value: stadium
        - name: PLAYER_TEAM
          value: visitors
        - name: PLAYER_COLOR
          value: yellow
        - name: PLAYER_NAME
          value: yellow goat
        - name: JAEGER_SERVICE_NAME
          value: ai-locals
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: 1
        - name: JAEGER_PROPAGATION
          value: b3
        - name: JAEGER_ENDPOINT
          value: http://jaeger-collector.istio-system.svc:14268/api/traces
        securityContext:
          privileged: false
